---
- hosts: all
  become: "{{ inventory_hostname != 'OpenVPN' }}"  # Conditionally enable become based on the host

  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
      when: inventory_hostname != 'OpenVPN'  # Conditionally run the task based on the host